### ISSUE TITLE
Use snapshots to automate testing

### ISSUE THREAD

**Issue by svenluijten** [simonhamp/the-og#3]
Instead of (only) relying on manual testing, we could implement something like [Spatie's snapshot assertions](https://github.com/spatie/phpunit-snapshot-assertions) to assert none of the previous features break when implementing something new. 

How do you feel about this? I'll be more than happy to implement it, just wanna gauge interest before I commit time to it 😄

**Comment by simonhamp** [comment]
Yeh I really like this idea 🙌🏼 

Will be a great way to reliably test different variations of layouts and themes and settings

My only concern is that doing it this early on, things could change a lot, so maybe it will not be that useful to implement just yet?

**Comment by svenluijten** [comment]
> My only concern is that doing it this early on, things could change a lot, so maybe it will not be that useful to implement just yet?

It's fairly trivial to update the snapshots, and as long as that is done consciously it's fine. I see snapshot testing more as regression testing (preventing bugs to sneak into previous features when implementing something else), and you (probably) wouldn't use it in a TDD-way. I'll see if I can get a PR in either today or tomorrow!
